### ISSUE TITLE
Reason went to https, and thus reasonable is no longer acting on Hit and Run pages.

### ISSUE THREAD

**Issue by yrona** [brymck/reasonable#2]
Hi Brian,

Reason went to https, and thus Reasonable is no longer acting on pages.

We are thus cast in a hell where troll comments taunt us, we have no idea who said what including us!

I think the fix is a simple one, changing line 23 on manifest.json.yml.

Could you hook us up, old friend?

**Comment by brymck** [comment]
Thanks, I've made this update. I had to fiddle with some other stuff to get it to compile (seriously questioning my choice of CoffeeScript), so I'm not 100% on whether there are any bugs, but at least what I checked of it seemed fine. Let me know if anything else is busted, though.
