### ISSUE TITLE
Inline youtube videos not showing up.

### ISSUE THREAD

**Issue by yrona** [brymck/reasonable#3]
Hi Brian,

Your recent work was greatly appreciated - you can see the hosanas in this mornings threads.

However, one bug has cropped up involving embedded youtube videos.  An example may be found here:

https://reason.com/blog/2015/09/21/alexis-tsipras-stepped-down-as-greek-pri#comment_5603046

I don't have a quick fix to recommend.  Can you take a stab at it? :)

**Comment by brymck** [comment]
Should be fixed in version 2.3.6 (80887b2905a26abce709e7a2891499736997bed3). The problem was that the YouTube (and Gravatar) links were using HTTP instead of HTTPS.

**Comment by yrona** [comment]
Works like a charm!!!  Thanks!
